name: All tests in one file
on: [workflow_dispatch]
  
 
jobs:
  Artifacts_are_generated:
    name: Check if artifacts are generated
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: Check if artifacts are generated or not
        run: |
           set -e
           grep -q testSquare test-results/results.xml
           grep -v sqNums code-coverage/coverage.xml

           
  All_test_picked_with_No_test_folder_given:
    name: All the tests are picked when no test folder is given
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: check if all the tests are picked or not
        run: |
           set -e
           grep -q testCalc5 test-results/results.xml
           grep -q testCalc2 test-results/results.xml
           grep -q testCalc4 test-results/results.xml
           
  Tests_can_be_filtered_by_tag:
    name: Tests can be filtered by tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          select-by-tag: TestSquare 
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: check if tests are filtered by tag
        run: |
           set -e
           grep -q testCalc2 test-results/results.xml
           
           
  No_tests_are_picked_for_incorrect_tag:
    name: No tests will be picked for incorrect tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          select-by-tag: TestSquareX
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: No tests are picked for incorrect tag value
        run: |
           set -e
           grep -c testCalc1 test-results/results.xml
           grep -c testCalc2 test-results/results.xml
           grep -c testCalc4 test-results/results.xml
           
           
  Tests_can_be_filter_by_folder:
    name: Tests can be filtered by folder
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          select-by-folder: test/temp
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: Check if tests can be filtered by folder
        run: |
           set -e
           grep -q testCalc2 test-results/results.xml
           
  No_tests_picked_for_incorrect_folder_path:
    name: No tests are picked for incorrect folder path
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          select-by-folder: test/tempp
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: Check that no tests are picked for incorrect folder path
        run: |
           set -e
           grep -q testCalc2 test-results/results.xml

           


    
