name: All tests in one file
on: [workflow_dispatch]
  
 
jobs:
  Artifacts_are_generated:
    name: Check if artifacts are generated
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: Check if artifacts are generated or not
        run: |
           set -e
           grep -q sqNums code-coverage/coverage.xml
#           grep -q testSquare test-results/results.xml
           
#   All_test_picked_with_No_test_folder_given:
#     name: All the tests are picked when no test folder is given
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Set up MATLAB
#         uses: matlab-actions/setup-matlab@v1
#       - name: Run tests and generate artifacts
#         uses: matlab-actions/run-tests@v1
#         with:
#           source-folder: src
#           test-results-junit: test-results/results.xml
#           code-coverage-cobertura: code-coverage/coverage.xml
#       - name: check if all the tests are picked or not
#         run: |
#            set -e
#            grep -q testCalc5 test-results/results.xml
#            grep -q testCalc2 test-results/results.xml
#            grep -q testCalc4 test-results/results.xml
           
#   Tests_can_be_filtered_by_tag:
#     name: Tests can be filtered by tag
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Set up MATLAB
#         uses: matlab-actions/setup-matlab@v1
#       - name: Run tests and generate artifacts
#         uses: matlab-actions/run-tests@v1
#         with:
#           source-folder: src
#           select-by-tag: TestSquare 
#           test-results-junit: test-results/results.xml
#           code-coverage-cobertura: code-coverage/coverage.xml
#       - name: check if tests are filtered by tag
#         run: |
#            set -e
#            grep -q testCalc2 test-results/results.xml


    
