name: Run MATLAB Command integration test cases
on: 
  workflow_dispatch:
    inputs:
      MatlabCommand:
        description: 'Command to run'     
        required: true
      releaseOption:
        description: 'Release Option for build'     
        required: true
jobs:
    Run_Matlab_command:
      name: Run Matlab Command
      runs-on: ubuntu-latest
      steps:
        - name: Install MATLAB
          uses: matlab-actions/setup-matlab@v0
          with:
            release: ${{ github.event.inputs.releaseOption }}
        - name: Run Matlab command
          uses: matlab-actions/run-command@v0
          with:
            command: ${{ github.event.inputs.MatlabCommand }}
