name: All tests combine
on: [workflow_dispatch]
jobs:
  my-job:
    name: setup Matlab
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
           release: R2020a
      - bash: |
          set -e
          matlab -batch "assert(strcmp(version('-release'),'2020a'))"
        displayName: Check matlab release
          
