name: Run the main file using this
on: push
jobs:
  trigger_the_other_file:
    strategy:
      matrix:
        files_to_run: [run_matlab_script.yml, summary_file.yml]
    name: Run other file
    runs-on: ubuntu-latest
    steps:
      - name: running the file
        shell: bash
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/viranch526/test_workflow/actions/workflows/${{matrix.files_to_run}}/dispatches \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' \
            -d '{"ref":"main"}' 
