name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job-test:
   name: Run MATLAB Script
   runs-on: ubuntu-latest
   steps:
     - name: cli run
       run: |
        gh version
        echo ${{secrets.GH_TOKEN}}
        export GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
        echo ${{github.job}}
        echo ${{github.run_id}}
        gh repo clone viranch526/test_workflow
        cd test_workflow
        ls
        gh run view ${{github.run_id}} --log | grep -c cli
        gh run view --job ${{github.job}} --log | grep -c test
