name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
            release: R2018b
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
#           select-by-folder: test/temp
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          test-results-pdf: test-results/results.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: All the reports
          path: |
            test-results/
            code-coverage/coverage.xml

          
