name: Run MATLAB Script on GitHub-Hosted Runner
on: workflow_dispatch
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.301
#       - name: Run script
#         uses: matlab-actions/run-command@v1
#         with:
#           command: myscript
