name: Differntiate Runners
on: workflow_dispatch
jobs:
    Build_fails_for_Invalid_command:
      env: 
        Runner: Github_Hosted               # we can write ${{ properties.runner}} here instead of Github_Hosted. Where runner will be a field in properties file.
      strategy:
            matrix:
                platform: [ubuntu-latest, ubuntu-18.04]
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2          
        - if: ${{ env.Runner == 'Github_Hosted' }}
          name: Install MATLAB          
          uses: matlab-actions/setup-matlab@v0
        - name: Run command
          uses: matlab-actions/run-command@v0

