name: Summary
on: push
# jobs:
#     Summary_File:
# #       strategy:
# #             matrix:
# #                 platform: [ubuntu-latest, ubuntu-18.04]
#       runs-on: ubuntu-latest
# #       continue-on-error: true
#       steps:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: ech "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - if: ${{ failure() }}
        name: The job has failed
        id: final_step1
        shell: bash
        run: |
          echo "Job1 is failed" > status.txt
      - if: ${{ failure() }}
        name: Upload status result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: status
          path: status.txt
      - if: ${{ success() }}
        name: The job has succeeded
        id: final_step2
        run: |
          echo "Job1 is succeeded"
        
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
