name: Summary
on: push
# jobs:
#     Summary_File:
# #       strategy:
# #             matrix:
# #                 platform: [ubuntu-latest, ubuntu-18.04]
#       runs-on: ubuntu-latest
# #       continue-on-error: true
#       steps:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
